# Generated by Django 5.1.1 on 2024-09-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='station_line',
        ),
        migrations.AddField(
            model_name='station',
            name='station_line',
            field=models.ManyToManyField(to='App1.line'),
        ),
    ]
